apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml

images:
  - name: dice3059/dice-backend
    newTag: "9-ac1976e"
