apiVersion: kustomize.config.k8s.io/v1kbeta1
kind: kustomize

resources:
  - configmap.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
images:
  - name: dice3059/dice-backend
    newTag: "0.0.2"